language: ruby

rvm:
  - 2.4.1

cache: bundler

gemfile:
  - Gemfile

before_install:
  - 'rm ${BUNDLE_GEMFILE}.lock'
  - gem update --system

after_install:
  - rails db:seed
  - rails spring rspec

notifications:
  email:
    on_pull_requests: false
    on_success: change
    on_failure: always

